name: master3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Downstream Workflow
        id: downstream
        uses: pauldraper/workflow-dispatch@v1.5
        with:
          marker-input: upstream-url
          ref: refs/heads/main
          repo: JanLipovsek/action_slave
          token: ${{ secrets.TOKEN }}
          wait: "true"
          workflow: slave3.yml

      - name: Print Outputs
        run: |
          echo "Conclusion: ${{ steps.downstream.outputs.conclusion }}"
          echo "Run ID: ${{ steps.downstream.outputs.run_id }}"
          echo "https://github.com/JanLipovsek/action_slave/actions/runs/${{steps.downstream.outputs.run_id}}" > $GITHUB_STEP_SUMMARY
