name: master3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Downstream Workflow
        uses: pauldraper/workflow-dispatch@v1.5
        with:
          marker-input: upstream-url
          ref: refs/heads/main
          repo: JanLipovsek/action_slave
          token: ${{ secrets.TOKEN }}
          wait: "true"
          workflow: slave3.yml
