# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test action

# Don't run this workflow concurrently 2
on:
  pull_request:
    branches: [ "main" ]
  push:
jobs:
  ping_slave:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
          ref: main # or refs/heads/target_branch
          repo: action_slave
          owner: JanLipovsek
          workflow: slave2.yml
          #workflow_inputs: { "some_input": "value" } # Optional
          workflow_timeout_seconds: 120 # Default: 300

      - name: Use the output run ID
        run: echo "https://github.com/JanLipovsek/action_slave/actions/runs/${{steps.return_dispatch.outputs.run_id}}"