name: DepthAI Core CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  ping_slave:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT asdssad
          ref: main # or refs/heads/target_branch
          repo: action_slave
          owner: JanLipovsek
          workflow: slave2.yml
          workflow_inputs: '{"some_input": "${{ github.run_id }}"}' # Optional
          workflow_timeout_seconds: 120 # Default: 300

      - name: Use the output run ID
        run: echo "https://github.com/JanLipovsek/action_slave/actions/runs/${{steps.return_dispatch.outputs.run_id}}"

      - name: Adding markdown
        run: echo "https://github.com/JanLipovsek/action_slave/actions/runs/${{steps.return_dispatch.outputs.run_id}}" >> $GITHUB_STEP_SUMMARY